### ISSUE TITLE
GitHub Review: Main Branch Protection Rule Issue

### ISSUE THREAD

**Issue by ujjwalnp** [Hunter-420/DevFlexPort#11]
# GitHub Review: Main Branch Protection Rule Issue

## Issue Description

The current main branch protection rules in the project repository pose challenges for collaborators in effectively contributing to the codebase. Two specific rules, 'Require a pull request before merging' and 'Require review from Code Owners,' are causing unnecessary obstacles for collaborators. Additionally, the 'Restrict deletions' rule hinders collaborators from managing the code directly.

### Problematic Rules:

1. **Require a pull request before merging:**
   - This rule can impede quick and direct contributions, especially for minor changes or bug fixes. It might be beneficial to evaluate whether this level of restriction is necessary for all contributors.

2. **Require review from Code Owners:**
   - While code reviews are essential, making it mandatory for Code Owners might lead to delays in the contribution process. Some changes may not necessarily require approval from Code Owners, and this rule might create unnecessary bottlenecks.

### Suggested Actions:

- **Review 'Require a pull request before merging':**
  - Consider relaxing this rule for trusted collaborators to streamline the contribution process. For larger changes, maintain the pull request process, but for minor edits, it may be beneficial to allow direct pushes.

- **Review 'Require review from Code Owners':**
  - Evaluate the necessity of mandatory Code Owner reviews for every change. This can be adjusted based on the nature and criticality of the changes. Critical changes might still require Code Owner reviews, while minor changes could proceed without this restriction.

- **Review 'Restrict deletions' rule:**
  - Collaborators often need to make quick adjustments or fixes directly in the main branch. Consider whether the 'Restrict deletions' rule is essential for all collaborators or if it could be adjusted to allow certain users to manage code more efficiently.

## Proposed Solution

A balanced approach to branch protection rules would encourage collaboration and make it easier for contributors to make positive contributions. The current strict rules, especially 'Require a pull request before merging' and 'Require review from Code Owners,' may need adjustment to strike the right balance between maintaining code quality and enabling efficient collaboration.

## Additional Notes

Feel free to discuss these proposed changes further and gather feedback from the team. The aim is to optimize the contribution process while ensuring the integrity and quality of the codebase.

**Comment by Hunter-420** [comment]
Refered to CONTRIBUTING.md for contribution guidelines
